[package]
name = "icurl"
version = "0.1.0"
authors = ["DuGlaser <duglaser0618@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
